from func.Sistem_func import *
from func.Create_new_dir import *
from func.Deldir import *
from func.Moving_b_folders import *
from func.Show_my_dir_now import *
from func.Create_new_file import *
from func.Write_text_in_file import *
from func.Cutfile import *
from func.Delfile import *
from func.Move_file import *
from func.Rename_file import *
from func.Exit_from_programm import *